name: marciomobile
description: Aplicativo Flutter para visualização de odds de jogos de futebol, consumindo a API FutPythonTrader.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  http: ^1.2.2

  # State Management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.5

  # Utils
  intl: ^0.19.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
